import * as fs from "fs";
import * as path from "path";
import { glob } from "glob";
import type { FileAnalysis, Manifest, ManifestEntry } from "./types.js";

const VIBE_DIR = ".vibe-reading";
const FILES_DIR = path.join(VIBE_DIR, "files");
const GLOBAL_DIR = path.join(VIBE_DIR, "global");

const IGNORE_PATTERNS = [
  "**/node_modules/**",
  "**/.git/**",
  "**/.vibe-reading/**",
  "**/dist/**",
  "**/out/**",
  "**/build/**",
  "**/*.min.js",
  "**/*.map",
  "**/package-lock.json",
  "**/yarn.lock",
  "**/pnpm-lock.yaml",
];

const CODE_EXTENSIONS = new Set([
  ".ts", ".tsx", ".js", ".jsx", ".py", ".rs", ".go",
  ".java", ".c", ".cpp", ".h", ".hpp", ".rb", ".php",
  ".swift", ".kt", ".scala", ".cs", ".lua", ".zig",
  ".vue", ".svelte", ".astro",
]);

async function main() {
  const projectRoot = process.argv[2] || process.cwd();
  console.log(`[vibe-reading] Analyzing: ${projectRoot}`);

  fs.mkdirSync(path.join(projectRoot, FILES_DIR), { recursive: true });
  fs.mkdirSync(path.join(projectRoot, GLOBAL_DIR), { recursive: true });

  const files = await glob("**/*", {
    cwd: projectRoot,
    nodir: true,
    ignore: IGNORE_PATTERNS,
    dot: false,
  });

  const sourceFiles = files.filter((f) =>
    CODE_EXTENSIONS.has(path.extname(f).toLowerCase())
  );

  console.log(`[vibe-reading] Found ${sourceFiles.length} source files`);

  const manifestEntries: ManifestEntry[] = [];

  for (const file of sourceFiles) {
    const absPath = path.join(projectRoot, file);
    try {
      const analysis = await analyzeFile(file, absPath);
      const outName = file.replace(/[/\\]/g, "__") + ".json";
      const outPath = path.join(projectRoot, FILES_DIR, outName);
      fs.writeFileSync(outPath, JSON.stringify(analysis, null, 2));

      manifestEntries.push({
        path: file,
        status: "analyzed",
        entity_count: analysis.entities.length,
      });

      console.log(`  [ok] ${file} → ${analysis.entities.length} entities`);
    } catch (err) {
      manifestEntries.push({ path: file, status: "failed", entity_count: 0 });
      console.error(`  [fail] ${file}: ${err}`);
    }
  }

  const manifest: Manifest = {
    project: path.basename(projectRoot),
    analyzed_at: new Date().toISOString(),
    total_files: sourceFiles.length,
    analyzed_files: manifestEntries.filter((e) => e.status === "analyzed").length,
    coverage: sourceFiles.length > 0
      ? manifestEntries.filter((e) => e.status === "analyzed").length / sourceFiles.length
      : 1,
    files: manifestEntries,
  };

  fs.writeFileSync(
    path.join(projectRoot, VIBE_DIR, "manifest.json"),
    JSON.stringify(manifest, null, 2)
  );

  console.log(
    `\n[vibe-reading] Done. Coverage: ${(manifest.coverage * 100).toFixed(1)}% ` +
    `(${manifest.analyzed_files}/${manifest.total_files})`
  );
}

async function analyzeFile(
  relativePath: string,
  absPath: string
): Promise<FileAnalysis> {
  const content = fs.readFileSync(absPath, "utf-8");
  const lines = content.split("\n");

  // Phase 0: stub extractor — generates placeholder entities from function/class definitions
  // Real extractors (Tree-sitter + LLM) will replace this in Phase 1
  const entities = extractStubEntities(relativePath, lines);

  return {
    file: relativePath,
    entities,
    analyzed_at: new Date().toISOString(),
  };
}

interface DataEntity {
  anchor: { file: string; start_line: number; start_col: number; end_line: number; end_col: number };
  type: "concept" | "flow" | "history" | "jump";
  summary: string;
  detail: Record<string, unknown>;
}

function extractStubEntities(file: string, lines: string[]): DataEntity[] {
  const entities: DataEntity[] = [];

  const patterns = [
    { regex: /^\s*(export\s+)?(async\s+)?function\s+(\w+)/, kind: "function" },
    { regex: /^\s*(export\s+)?class\s+(\w+)/, kind: "class" },
    { regex: /^\s*(export\s+)?interface\s+(\w+)/, kind: "interface" },
    { regex: /^\s*def\s+(\w+)/, kind: "function" },
    { regex: /^\s*class\s+(\w+)/, kind: "class" },
  ];

  for (let i = 0; i < lines.length; i++) {
    for (const { regex, kind } of patterns) {
      const match = lines[i].match(regex);
      if (match) {
        const name = match[match.length - 1];
        entities.push({
          anchor: {
            file,
            start_line: i + 1,
            start_col: 0,
            end_line: i + 1,
            end_col: lines[i].length,
          },
          type: "concept",
          summary: `${kind}: ${name}`,
          detail: {
            description: `[Stub] ${kind} "${name}" — real analysis will be generated by Tree-sitter + LLM in Phase 1.`,
            kind,
            name,
          },
        });
        break;
      }
    }
  }

  return entities;
}

main().catch((err) => {
  console.error("[vibe-reading] Fatal:", err);
  process.exit(1);
});
